name: Pipeline DevOps CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Fazer checkout do código
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 3. Instalar dependências
        working-directory: ./backend
        run: npm install

      - name: 4. Executar testes
        working-directory: ./backend
        run: npm test

      - name: 5. Verificar versão do Node.js
        run: node -v

      - name: 6. Listar arquivos do projeto
        run: ls -la

      - name: 7. Simular deploy
        run: echo "Deploy realizado com sucesso!"
